---
name: Sonarr proxy
version: 0.2.4
slug: sonarr_proxy
description: nginx reverse proxy to expose Sonarr through HA ingress
webui: "[PROTO:ssl]://[HOST]"
init: false
ingress: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - ssl
options:
  destination: "http://192.168.1.55:8989"
schema:
  destination: str?
