name: Sonarr Proxy
version: "1.0.0"
panel_icon: "mdi:television"
panel_title: Sonarr Proxy
slug: sonarr-proxy
description: Proxy addon for Sonarr
url: "https://github.com/SCCMOG/home-assistant-addons"
startup: application
boot: auto
webui: "http://[HOST]:[PORT:8989]/"
watchdog: "http://[HOST]:[PORT:8989]/"
ingress: true
ingress_port: 8989
ingress_entry: /
panel_admin: false
ports:
  8989/tcp: 8989
ports_description:
  8989/tcp: Web interface (Not required for Hass.io Ingress)
host_network: false
devices: []
usb: false
tmpfs: false
full_access: false
environment: {}
options:
  server: "192.168.1.55:8989"
schema:
  server: "match(^.+:\\d+$)"
services: []
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map: []
