---
name: Ingress proxy
version: 0.2.5
slug: ingress_proxy
description: nginx reverse proxy to expose network resources through HA ingress
webui: "HTTP://[HOST]:[PORT:8989]"
init: false
ingress: true
arch:
  - arch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - ssl
options:
  destination: "192.168.1.55:8989"
schema:
  destination: str?
