---
name: Ingress proxy Mod
version: 0.2.5
slug: ingress_proxy_mod
description: nginx reverse proxy to expose network resources through HA ingress
webui: "[PROTO:ssl]://[HOST]:[PORT:8989]"
init: false
ingress: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  destination: "http://192.168.0.1"
schema:
  destination: str?
